name: Keep Alive
on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:
jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Streamlit app
        run: |
          curl -S --fail --silent --show-error \
          https://ssu-energy-dashboard-usb4padbsjz7yz8tdq36zz.streamlit.app/
